import getMeetups from './getMeetups';
import userAction from './userAction';

const {
  USER_LOGIN,
  USER_REGISTER,
  AUTHENTICATION_ERROR,
  AUTHENTICATION_SUCCESS
} = userAction;
const { GET_ALL_MEETUPS, MEETUP_NOTFOUND, GET_SINGLE_MEETUP } = getMeetups;

export {
  USER_LOGIN,
  USER_REGISTER,
  GET_ALL_MEETUPS,
  AUTHENTICATION_ERROR,
  AUTHENTICATION_SUCCESS,
  GET_SINGLE_MEETUP,
  MEETUP_NOTFOUND
};
