
export const GET_ALL_MEETUPS = 'GET_ALL_MEETUPS';
export const GET_SINGLE_MEETUP = 'GET_SINGLE_MEETUP';
export const MEETUP_NOTFOUND = 'MEETUP_NOTFOUND';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_REGISTER = 'USER_REGISTER';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const GET_MEETUP_ID = 'GET_MEETUP_ID';
