// Authentication Action types
export const USER_LOGIN = 'USER_LOGIN';
export const USER_REGISTER = 'USER_REGISTER';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
// Meetups Action types
export const GET_ALL_MEETUPS = 'GET_ALL_MEETUPS';
export const GET_SINGLE_MEETUP = 'GET_SINGLE_MEETUP';
export const MEETUP_NOTFOUND = 'MEETUP_NOTFOUND';
export const GET_MEETUP_ID = 'GET_MEETUP_ID';
export const CREATE_MEETUP = 'CREATE_MEETUP';
export const ERROR_MEETUP = 'ERROR_MEETUP';
export const DELETE_MEETUP = 'DELETE_MEETUP';
