const userAction = {
  USER_LOGIN: 'USER_LOGIN',
  USER_REGISTER: 'USER_REGISTER',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHENTICATION_SUCCESS: 'AUTHENTICATION_SUCCESS'
};

export default userAction;
